language: ruby

rvm:
- 2.2.2
- 2.3.3
- 2.4.0
- 2.5.0
- ruby-head

before_install:

- sudo gem uninstall travis
- sudo gem install travis -v 1.8.8 --no-rdoc --no-ri
- gem update --system --no-document
- gem install bundler -v 1.11.2
- bundle install

branches:
    only:
        - master
        - develop
        - /^develop-.*/
        - /^bugfix.*/
        - /^feature.*/

matrix:
  allow_failures:
  - rvm: ruby-head

sudo: false

script:
- bundle exec rspec
