language: ruby

rvm:
- 2.2.2
- 2.3.3
- 2.4.0
- 2.5.0
- ruby-head

before_install:
- travis_retry gem update --system || travis_retry gem update --system 2.7.8

install:
  # - gem uninstall bundler
- travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v 1.17.3
- bundle install

branches:
    only:
        - master
        - develop
        - /^develop-.*/
        - /^bugfix.*/
        - /^feature.*/

matrix:
  allow_failures:
  - rvm: ruby-head

sudo: false

script:
- bundle exec rspec
